### ISSUE TITLE
1.13 - Can't lock any skulls

### ISSUE THREAD

**Issue by Platinteufel** [Tsuser1/Modern-LWC#16]
**LWC Version (/lwc admin version):** 

2.1.0-dev-8f0b3a1/

**Server version (/version):** 

git-Spigot-2440e18-997d378 (MC: 1.13.1)

**Detailed description of problem:**

In 1.13 I'm not able to lock any skull item. I've added those entries to core.yml

        LEGACY_SKULL:
            enabled: true
            autoRegister: private
        LEGACY_SKULL_ITEM:
            enabled: true
            autoRegister: private
        WITHER_SKELETON_SKULL:
            enabled: true
            autoRegister: private
        WITHER_SKELETON_WALL_SKULL:
            enabled: true
            autoRegister: private
        SKELETON_WALL_SKULL:
            enabled: true
            autoRegister: private
        SKELETON_SKULL:
            enabled: true
            autoRegister: private

I also cannot lock them manually by using the **/lock** command, so i guess LWC does not recognize my entries at all.

**Comment by pop4959** [comment]
I'm able to lock these on my end. Your core.yml might be incorrect. My best guess is that either your spacing is incorrect, or you should not be capitalising block names.

My core.yml has the following entries added:

```
        skeleton_skull:
            enabled: true
            autoRegister: private
        skeleton_wall_skull:
            enabled: true
            autoRegister: private
        wither_skeleton_skull:
            enabled: true
            autoRegister: private
        wither_skeleton_wall_skull:
            enabled: true
            autoRegister: private
        zombie_head:
            enabled: true
            autoRegister: private
        zombie_wall_head:
            enabled: true
            autoRegister: private
        player_head:
            enabled: true
            autoRegister: private
        player_wall_head:
            enabled: true
            autoRegister: private
        creeper_head:
            enabled: true
            autoRegister: private
        creeper_wall_head:
            enabled: true
            autoRegister: private
        dragon_head:
            enabled: true
            autoRegister: private
        dragon_wall_head:
            enabled: true
            autoRegister: private
```

Proof that it works: [https://gyazo.com/c0a40f77abb9f4abd2f40c691f767dec](https://gyazo.com/c0a40f77abb9f4abd2f40c691f767dec)
