### ISSUE TITLE
Current state of entity locking overhaul?

### ISSUE THREAD

**Issue by mibby** [Tsuser1/Modern-LWC#41]
@Tsuser1, @pop4959 

I was reading the wiki and noticed entity locking is currently not supported and being redeveloped.
https://github.com/Tsuser1/Modern-LWC/wiki/Entity-Locking

Is entity locking currently functional at all? If not, perhaps you could look into merging some changes made to dmulloy's lwc fork which adds entity locking support? https://github.com/dmulloy2/LWC

It supports adding an entity section below blocks in the main config.
i.e.
```
    blocks:
        chest:
            enabled: true
    entities:
        armor_stand:
            enabled: true
        painting:
            enabled: true
        item_frame:
            enabled: true
        minecart_chest:
            enabled: true
        SKULL_ITEM:
            enabled: true
```
