### ISSUE TITLE
autoRegister: donation does not working

### ISSUE THREAD

**Issue by ghost** [Tsuser1/Modern-LWC#72]
**LWC Version (/lwc admin version):** 
`2.1.1-46e9fa0`

**Server version (/version):** 
`Paper-446`

**Short five word summary of issue:** 
LWC don't want to auto register a donation type

**Detailed description of problem:**
Here's my example `core.yml`:
```yml
chest:
  enabled: true
  autoRegister: donation
hopper:
  enabled: true
  autoRegister: donation
```

**If there was an error in console, put it here:**
Possibly just missing feature, there's no error
